import React from "react";
import img from "../images/me.jpg"

function About() {
  return <div className="about">
    <img className="me" src={img}  alt="avatar"/>
    
    <p>LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT.
       VIVAMUS ET CONDIMENTUM MI. MORBI ET DICTUM MI. CRAS MALESUADA EU NULLA EU GRAVIDA.
      SUSPENDISSE ULTRICIES ANTE NULLA, SIT AMET VULPUTATE URNA FAUCIBUS PULVINAR. 
      VIVAMUS EGET PURUS QUIS FELIS FAUCIBUS INTERDUM. DONEC MAXIMUS NULLA COMMODO FELIS 
      RUTRUM, UT FERMENTUM AUGUE LOBORTIS. ETIAM NON JUSTO MAXIMUS, ACCUMSAN RISUS AC, 
      CONDIMENTUM EROS. MORBI IMPERDIET VIVERRA EROS EU VENENATIS. INTEGER MAURIS VELIT, 
      VIVERRA EGET JUSTO EGET, DICTUM PELLENTESQUE NISL. AENEAN LIBERO DIAM, ULTRICIES 
      DICTUM EROS A, TEMPUS BLANDIT LOREM. MAECENAS DICTUM EFFICITUR MASSA EGET FINIBUS. 
      ETIAM EGET MASSA NEC SEM VOLUTPAT MALESUADA UT ID NULLA. MAECENAS VITAE ANTE 
      CONSECTETUR, ORNARE NUNC A, RUTRUM EST.</p>
    </div>;
}

export default About;
